- name: Print a value from SSM
  hosts: localhost
  tasks:
    - name: Print Value
      ansible.builtin.debug:
        msg: "{{ lookup('amazon.aws.aws_ssm', 'test-password', region='us-east-1' ) }}"

